INPUT_FASTA = "data/candidate_proteins.fasta"
OUTPUT_FASTA = "results/multi_epitope_vaccine.fasta"

CTL_LENGTH = 9
HTL_LENGTH = 15
BCL_LENGTH = 12

MAX_SELECTED = 5

ADJUVANT = "GIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK"

CTL_LINKER = "AAY"
HTL_LINKER = "GPGPG"
BCL_LINKER = "KK"

BLOCK_LINKER = "EAAAK"
